version: '3.8'

networks:
  default:
    driver: bridge

services:
  postgres:
    image: postgres:16.3
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - default
    
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - default

  # pgadmin:
  #   image: dpage/pgadmin4:8.13.0
  #   restart: always
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8888:80"
  #   env_file:
  #     - .env
  #   networks:
  #     - default

volumes:
  postgres:
    driver: local